### ISSUE TITLE
Still getting fatal exception from org.intermine.model.bio.OrganismShadow.setoBJECT

### ISSUE THREAD

**Issue by sammyjava** [intermine/intermine#1834]
I've completely rebuilt a soymine with the newest code, and I'm still getting fatal runtime exceptions from XShadow from this line (for example):
```
if ((i < notXml.length) && "avariety".equals(notXml[i])) {
```
Since most objects extend BioEntity, which references Organism, this error breaks pretty much all queries and report pages. It appears that I can query objects which are entirely custom (e.g. QTL, GeneticMarker, LinkageGroup) as long as I don't include a core model reference. For example, I can query LinkageGroup.primaryIdentifier; or LinkageGroup.primaryIdentifier + LinkageGroup.QTLs.primaryIdentifier; but as soon as I add, say, QTLs.organism into the query, it breaks.

So I conclude that we've still got a fight going on between the core model and the full mine model. I'll give it one more run doing some extra cleaning before my installs.
```
26-Jun-2018 10:51:35.432 SEVERE [ajp-nio-8009-exec-18] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [action] in context with path [/soymine] threw exception [javax.servlet.ServletException: javax.servlet.jsp.JspException: ServletException in '/report.jsp': javax.servlet.jsp.JspException: ServletException in '/reportRefsCols.jsp': /reportRefsCols.jsp(61,10) '${collection.table}' Error reading [table] on type [org.intermine.web.logic.results.DisplayReference]] with root cause
 java.lang.IllegalArgumentException: Unknown field avariety
	at org.intermine.model.bio.OrganismShadow.setoBJECT(OrganismShadow.java:320)
	at org.intermine.objectstore.intermine.NotXmlParser.parse(NotXmlParser.java:179)
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.internalGetObjectByIdWithConnection(ObjectStoreInterMineImpl.java:1823)
	at org.intermine.objectstore.intermine.ObjectStoreInterMineImpl.internalGetObjectById(ObjectStoreInterMineImpl.java:1780)
	at org.intermine.objectstore.ObjectStoreAbstractImpl.getObjectById(ObjectStoreAbstractImpl.java:205)
	at org.intermine.objectstore.proxy.ProxyReference.getObject(ProxyReference.java:52)
	at org.intermine.web.logic.results.InlineResultsTable.<init>(InlineResultsTable.java:122)
	at org.intermine.web.logic.results.InlineResultsTable.<init>(InlineResultsTable.java:148)
	at org.intermine.web.logic.results.DisplayField.getTable(DisplayField.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:94)
	at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:110)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
	at org.apache.jasper.el.JspValueExpression.getValue(JspValueExpression.java:115)
	at org.apache.jsp.reportRefsCols_jsp._jspx_meth_c_005fset_005f10(reportRefsCols_jsp.java:1032)
	at org.apache.jsp.reportRefsCols_jsp._jspx_meth_c_005fwhen_005f0(reportRefsCols_jsp.java:896)
	at org.apache.jsp.reportRefsCols_jsp._jspx_meth_c_005fchoose_005f0(reportRefsCols_jsp.java:850)
	at org.apache.jsp.reportRefsCols_jsp._jspx_meth_c_005fforEach_005f0(reportRefsCols_jsp.java:482)
	at org.apache.jsp.reportRefsCols_jsp._jspx_meth_c_005fif_005f0(reportRefsCols_jsp.java:325)
	at org.apache.jsp.reportRefsCols_jsp._jspService(reportRefsCols_jsp.java:186)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:894)
	at org.apache.jasper.runtime.PageContextImpl.doInclude(PageContextImpl.java:679)
	at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:673)
	at sun.reflect.GeneratedMethodAccessor213.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.struts.tiles.TilesUtilImpl.doInclude(TilesUtilImpl.java:129)
	at org.apache.struts.tiles.TilesUtil.doInclude(TilesUtil.java:152)
	at org.apache.struts.tiles.taglib.InsertTag.doInclude(InsertTag.java:764)
	at org.apache.struts.tiles.taglib.InsertTag$InsertHandler.doEndTag(InsertTag.java:896)
	at org.apache.struts.tiles.taglib.InsertTag.doEndTag(InsertTag.java:465)
	at org.apache.jsp.report_jsp._jspx_meth_tiles_005finsert_005f12(report_jsp.java:3010)
	at org.apache.jsp.report_jsp._jspx_meth_c_005fwhen_005f0(report_jsp.java:463)
	at org.apache.jsp.report_jsp._jspx_meth_c_005fchoose_005f0(report_jsp.java:266)
	at org.apache.jsp.report_jsp._jspService(report_jsp.java:207)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527)
	at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:894)
	at org.apache.jasper.runtime.PageContextImpl.doInclude(PageContextImpl.java:679)
	at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:673)
	at sun.reflect.GeneratedMethodAccessor213.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.struts.tiles.TilesUtilImpl.doInclude(TilesUtilImpl.java:129)
	at org.apache.struts.tiles.TilesUtil.doInclude(TilesUtil.java:152)
	at org.apache.struts.tiles.taglib.InsertTag.doInclude(InsertTag.java:764)
	at org.apache.struts.tiles.taglib.InsertTag$InsertHandler.doEndTag(InsertTag.java:896)
	at org.apache.struts.tiles.taglib.InsertTag.doEndTag(InsertTag.java:465)
	at org.apache.jsp.layout_jsp._jspx_meth_tiles_005fget_005f1(layout_jsp.java:1209)
	at org.apache.jsp.layout_jsp._jspService(layout_jsp.java:283)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
	at org.apache.struts.action.RequestProcessor.doForward(RequestProcessor.java:1083)
	at org.apache.struts.tiles.TilesRequestProcessor.doForward(TilesRequestProcessor.java:295)
	at org.apache.struts.tiles.TilesRequestProcessor.processTilesDefinition(TilesRequestProcessor.java:271)
	at org.apache.struts.tiles.TilesRequestProcessor.internalModuleRelativeForward(TilesRequestProcessor.java:370)
	at org.apache.struts.action.RequestProcessor.processForward(RequestProcessor.java:566)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:212)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.intermine.web.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:139)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:486)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by julie-sullivan** [comment]
Stupid question, `avariety` is the correct field? In addition to `variety`?

**Comment by julie-sullivan** [comment]
Yes you are exactly right, it's using the core InterMine model's version of Organism instead of yours. A clean should fix this.

**Comment by sammyjava** [comment]
ALL fields get an "a" prepended in that routine. That's the code for "variety." Here's an example from core bio-sources uniprot loader for primaryIdentifier:
```
uniprot/build/gen/org/intermine/model/bio/UTRShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/GeneFlankingRegionShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/SequenceFeatureShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/BioEntityShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/IntronShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/ChromosomeShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/CDSShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/GeneShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/TranscriptShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/SequenceCollectionShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/ExonShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
uniprot/build/gen/org/intermine/model/bio/ProteinShadow.java:            if ((i < notXml.length) && "aprimaryIdentifier".equals(notXml[i])) {
```

**Comment by sammyjava** [comment]
I did a clean, blew away all my .m2 and .gradle files, clean install. Still have the problem.

**Comment by sammyjava** [comment]
1. https://github.com/LegumeFederation/soymine

2. Organism model is fine:
```
<class name="Organism" is-interface="true">
        <attribute name="variety" type="java.lang.String"/>
        <attribute name="description" type="java.lang.String"/>
        <attribute name="chadoId" type="java.lang.Integer"/>
        <attribute name="species" type="java.lang.String"/>
        <attribute name="genus" type="java.lang.String"/>
        <attribute name="taxonId" type="java.lang.Integer"/>
        <attribute name="name" type="java.lang.String"/>
        <attribute name="commonName" type="java.lang.String"/>
        <attribute name="shortName" type="java.lang.String"/>
</class>
```

3. Version in the database also is correct:
```
       | <class name="Organism" is-interface="true">                                                                           +| 
       |         <attribute name="variety" type="java.lang.String"/>                                                           +| 
       |         <attribute name="description" type="java.lang.String"/>                                                       +| 
       |         <attribute name="chadoId" type="java.lang.Integer"/>                                                          +| 
       |         <attribute name="species" type="java.lang.String"/>                                                           +| 
       |         <attribute name="genus" type="java.lang.String"/>                                                             +| 
       |         <attribute name="taxonId" type="java.lang.Integer"/>                                                          +| 
       |         <attribute name="name" type="java.lang.String"/>                                                              +| 
       |         <attribute name="commonName" type="java.lang.String"/>                                                        +| 
       |         <attribute name="shortName" type="java.lang.String"/>                                                         +| 
       | </class>                                                                                                              +|
```

4. org.intermine dir DOES exist and was created AFTER I did the blowing away and cleaning:
---
[shokin@shokin-mines soymine]$ ls -l ~/.gradle/caches/modules-2/files-2.1/org.intermine/
total 0
drwxrwxr-x. 3 shokin shokin 31 Jun 26 11:04 bio-core
drwxrwxr-x. 3 shokin shokin 31 Jun 26 11:04 bio-model
drwxrwxr-x. 3 shokin shokin 31 Jun 26 13:20 bio-postprocess
drwxrwxr-x. 3 shokin shokin 31 Jun 26 15:29 bio-postprocess-create-attribute-indexes
drwxrwxr-x. 3 shokin shokin 31 Jun 26 15:32 bio-postprocess-create-autocomplete-index
drwxrwxr-x. 3 shokin shokin 31 Jun 26 15:32 bio-postprocess-create-search-index
drwxrwxr-x. 3 shokin shokin 31 Jun 26 15:31 bio-postprocess-summarise-objectstore
drwxrwxr-x. 3 shokin shokin 19 Jun 26 11:04 bio-source-flymine-static
drwxrwxr-x. 3 shokin shokin 31 Jun 26 15:27 bio-webapp
drwxrwxr-x. 3 shokin shokin 31 Jun 26 12:42 intermine-api
drwxrwxr-x. 3 shokin shokin 31 Jun 26 11:04 intermine-integrate
drwxrwxr-x. 3 shokin shokin 31 Jun 26 12:44 intermine-jbrowse-endpoint
drwxrwxr-x. 3 shokin shokin 31 Jun 26 11:04 intermine-model
drwxrwxr-x. 3 shokin shokin 31 Jun 26 11:04 intermine-objectstore
drwxrwxr-x. 3 shokin shokin 31 Jun 26 12:42 intermine-pathquery
drwxrwxr-x. 3 shokin shokin 31 Jun 26 11:04 intermine-resources
drwxrwxr-x. 3 shokin shokin 31 Jun 26 12:42 intermine-webapp
drwxrwxr-x. 3 shokin shokin 31 Jun 26 12:42 intermine-webtasks
```
So I'll try to track that down. I gather I should not build a mine if that dir exists.

**Comment by julie-sullivan** [comment]
I've made some updates to your mine to match the new system with the model being in `biomodel` now.

Maybe just delete the directory before deploying the webapp, after installing. Just to make sure they aren't being used.

**Comment by sammyjava** [comment]
This got fixed at some point.
